"project_id": "378913"
"api_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6IjY0MDRiZTFlOGIyOTVhNzg2ZGEyYmI0MmZmYjAwN2MyYmQ3MmM4MGI0YzJhZGEzNTk4MzBmMjEzZjQ4ZGFhNDkxYTcyNjgwYjJiYzFkOTUyIiwiaWF0IjoxNzIyODYzNDcxLjcwNDc3NywibmJmIjoxNzIyODYzNDcxLjcwNDc3OSwiZXhwIjoxNzU0Mzk5NDcxLjYyOTI5Mywic3ViIjoiMTUyNDUwMTYiLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.dLOqTsIngzAsXnrh2PRnzAtZVtosy0dnIPWViL9kVYnxGCGL3LJMPZ_cji-G9aHPhgmxERmBNeMp4Pynw7Y7NbtpT0QmgL9Gn6Ljjd5TTGwwS1UX81m-l69J6wTd1sRufs8X9vIAkxp-3boW7N0BkasBm9gRr_fBlnOFX_yV6mYj-gB5bRxI2CmakUcRVVZFk7hNfRT1LZnn60ghSllSoXM4dGF647Ey_Qm8kgerVqy1cshKc1X8jBKVLTXPTPnIpTESp4pFFbmDUlcnvvLa76FbW-5qBDXjPIEl6ASCqR8pIRV8Bh3n6-oaean7WBb_ZwPkrwxVczGlRd2io8xhVpQq33P6ebSnHp8hZFGS7kYyBZqBRfgzYTBSnNUCTWd-SQJzVeGiqzO-Qodi30X4AA7_nDYNun_soY3ma5sJsdaq2muMKXP2uWV9epLHp-VSTcIWEki0ozZqHKkUVlfzoWhtBKfQbLa5G48LQB9PVgOj3CQ4qgY8FPPdPk29-R_ytnQkXFTHXpudH0Ga_hrM7xtqYNmCttAVYZMGRoFZqH8GZs5KjSG2c0F9-x0554qi0fLgczJDOW15zjwZXRyUtqTD4SGaKQPvtYQn6AxBVRsUlLVUpPH7OLo8Kn7gMu3bx6fJhIURC6kA_Ap9YEgcnMRTuY_pTXSJi3VCJqP2iSw"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
files: [
  {
    "source": "/Telegram/**/en.lproj/NiceLocalizable.strings",
    "dest": "iOS/nicegram-client/%original_file_name%",
    "translation": "/Telegram/**/%two_letters_code%.lproj/%original_file_name%"
  }
]
